### PR TITLE
Project development

### PR DESCRIPTION
**Pull request by acolombo1**
- Choose an API to get numeric values based on a parameter [https://api.coinpaprika.com/](https://api.coinpaprika.com/).
- Follow these [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), including colors, typography and layout.
- When the page loads, the webapp shows the list of coins that can be filtered out by rank.
- Along with the coin name, display market cap numeric values that come from the API.
- When the user clicks (or taps) on a coin item, the application navigates to the details page.
- In the details page, the webapp retrieves data from the API to show detailed data for the coin.
- When the user clicks on the "Back" button (<), the user navigates to the home page.
- Create unit tests for pure functions in Redux code.
- Create integration tests for the application using the React Testing Library.
- The project is a single-page application (SPA) built with React and Redux.
- The data retrieved from the API is stored in the Redux store, and is filtered using a Filter stateless component.
- Every page (the main page and the pages for each item) has a unique route within the SPA.
- The project is deployed and accessible online (follow the link provided in the README file).

### CODE REVIEW

**Review by OLIPLICHE — CHANGES_REQUESTED** [review]
Hi @acolombo1 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

Linter is green (the last commit have a green check mark (✅)) 👏
README file is descriptive 👏
Commit messages are meaningful 👏 👏
Github flow is correctly used (Pull Request is made from the feature branch into the main branch) 👏
The test has passed👏 :
a

## Required Changes ♻️

- [x] Nice Job so far. Please, you need to record a video presenting the features of the project.



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by acolombo1** [comment]
Hi @OLIPLICHE : if you see my request review in the additional info there is the link to the video. Please tell me if you can see it.
Thanks

**Comment by OLIPLICHE** [comment]
> Hi @OLIPLICHE : if you see my request review in the additional info there is the link to the video. Please tell me if you can see it. Thanks

Please Can't see it. Kindly make it visible and submit the PR. the next reviewer going to check it.

**Review by keroloussamy — APPROVED** [review]
Hi @acolombo1, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

clap



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
